DROP TABLE IF EXISTS flights;

CREATE TABLE flights (
    "ID" BIGINT PRIMARY KEY,
    "FLIGHT_NUMBER" VARCHAR(50) NOT NULL,
    "AIRLINE" VARCHAR(100) NOT NULL,
    "SCHEDULED_TIME" TIMESTAMP NOT NULL,
    "ACTUAL_TIME" TIMESTAMP,
    "STATUS" VARCHAR(20) NOT NULL,
    "DELAY_MINUTES" INT,
    "CREATED_AT" TIMESTAMP NOT NULL
);
